language: c

os:
  - linux
  - osx

install:
  - git clone --depth=1 https://github.com/lmdb/lmdb
  - cd lmdb/libraries/liblmdb
  - make
  - sudo make install
  - cd -

script:
  - make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo make install; fi
  - make test
